host:
  id: 3
  name: deployd3
  os: linux
  architecture: amd64
  internal_address: deployd3 # can use ip

# base raft configuration for deployed apps
raft:
  replica_id: 3
  base_node_host_dir: "/data"
  base_wal_dir: "/data"

http:
  public:
    address: ":9600"
    fqdn: http://localhost:9403

ui:
  dir: "/var/www"

storage:
  s3:
    blob:
      endpoint: minio:9000
      key_id: <secret>
      key_secret: <secret>
      use_ssl: false
      bucket_name: sewatenan-bucket
      base_public_url: http://localhost:9000/sewatenan-bucket
  file:
    config-data: "/data/deployd/config.db"
    job-data: "/data/deployd/job.db"
