name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify tag is on main
        run: |
          git fetch origin main

          if ! git merge-base --is-ancestor "$GITHUB_SHA" origin/main; then
            echo "❌ Tagged commit is not contained in main."
            exit 1
          fi

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Run tests
        run: |
          go test -v ./internal/... ./src/...

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
            go build \
              -trimpath \
              -ldflags="-s -w" \
              -o deployd \
              cmd/deployd/*.go

      - name: Archive
        run: |
          tar -czf deployd-linux-amd64.tar.gz deployd

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: deployd-linux-amd64.tar.gz
